site_name: webdataset
repo_url: http://github.com/webdataset/webdataset
docs_dir: docs
site_dir: site
theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 3

nav:
    - README: index.md
    - WebDataset: webdataset.md
    - WIDS: wids.md
    - FAQ: FAQ.md
    - Examples:
      - examples/generate-text-dataset.md
      - examples/tesseract-wds.md
      - examples/train-resnet50-wds.md
      - examples/train-resnet50-wids.md
      - examples/train-resnet50-multiray-wds.md
      - examples/train-resnet50-multiray-wids.md
      - examples/train-ocr-errors-hf.md
      - examples/mi-images.md
      - examples/mi-prompts.md
      - examples/wds-notes.md
      - examples/column-store.md
